### ISSUE TITLE
Wrap booleans at `||` or `&&` and not at `==`

### ISSUE THREAD

**Issue by BriungRi** [movebit/movefmt#12]
I think it is much more readable to wrap at a boolean operator like "or" or "and" because each argument I can evaluate for `true` or `false` individually. Whereas for `==`, I like to have both sides of the argument in context when reading for equality, so it is nicer to keep this on the same line when possible.

![Screenshot 2024-06-10 at 9 13 26 AM](https://github.com/movebit/movefmt/assets/8957844/9a7aa812-c114-4963-8da4-c01f20752fb5)

**Comment by robinlzw** [comment]
We will optimize this area, thank you for your discovery.

**Comment by robinlzw** [comment]
We have added a test case for this issue here(https://github.com/movebit/movefmt/commit/8193e9f3423c240a7f59581b670380c1cdc9a87f) and found that after testing, the problem you reported does not exist. Furthermore, we have identified a similar scenario in the existing cases that is also handled correctly, which you can refer to [here](https://github.com/movebit/movefmt/blob/develop/tests/break_line/input2.fmt.move).
